Tests con c.c. PEC, PMC y periodico
lmdiazangulo/MCFNL2024 pull request #3
Opened 2024-03-25 09:57 UTC by armador1

2024-03-25 11:35 UTC, lmdiazangulo requested changes
Class has repeated methods

2024-03-25 11:35 UTC, lmdiazangulo commented on test_fdtd.py
> +    def getH(self):
This method is repeated

2024-03-25 12:48 UTC, armador1 commented on test_fdtd.py
> +    def getH(self):
Solved

2024-04-02 11:42 UTC, lmdiazangulo approved these changes

2024-04-02 11:48 UTC, merged